# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53a3789a436779fbe190c9266d302108f0678127da36f2a237b2883c287a5d38f3b699c8a4b9686b01100987a1a77afd51db3a669ae33674c36860ac9ae1ce8e

test:
  secret_key_base: cb74f0fe3fb72484b16ea1bf23dcdfad78c51e824c9599690b65958d64d24da919f6a24ba88b0a83f69639a656a8c1cb2087187d329f08fcc1ac1fc3a20394d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
